### ISSUE TITLE
New branded application icon

### ISSUE THREAD

**Issue by PavielKraskouski** [Saydullin/BSUIR_Schedule#3]
I propose to add a new branded application icon.

![Icon1](https://user-images.githubusercontent.com/9061796/218204825-b06e1f93-80e4-4554-93ef-1e522553cfc4.svg) ![Icon2](https://user-images.githubusercontent.com/9061796/218204997-ed5d33d2-8762-4a5e-9611-bc4954d57f29.svg)

Foreground layer:

![Foreground1](https://user-images.githubusercontent.com/9061796/218205549-ff06365e-6843-4f2c-b5ae-67c14dcb94fa.svg) ![Foreground2](https://user-images.githubusercontent.com/9061796/218205567-78c36ab8-e675-448f-b067-acefd55d7075.svg)

Background layer:

![Background1](https://user-images.githubusercontent.com/9061796/218205623-ff8a2489-39b0-4ce5-a529-6d245fc5781d.svg) ![Background2](https://user-images.githubusercontent.com/9061796/218205620-26c56d52-623a-4f1f-aa29-8db69f30ffe5.svg)

Monochrome:

![Monochrome](https://user-images.githubusercontent.com/9061796/218205752-9b2c5d77-79bf-4bc5-91d0-02cea0d1c33e.svg)

Google Play:

![GooglePlay1](https://user-images.githubusercontent.com/9061796/218251377-98404e57-8838-4d3d-b37e-f227e7494235.svg)
![GooglePlay2](https://user-images.githubusercontent.com/9061796/218251383-8c11f88c-3d02-430b-9b01-20c98fe04af6.svg)

**Comment by Saydullin** [comment]
These icons are much better than the original ones.
Thanks, I'll replace them!
